import { motion } from "framer-motion";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Button } from "@/components/ui/button";
import { Printer, Copy, TrendingUp, AlertTriangle, ShieldCheck, Newspaper, DollarSign } from "lucide-react";
import { toast } from "sonner";
import { Progress } from "@/components/ui/progress";

export function InvestmentReport({ data }: { data: any }) {
  const handlePrint = () => {
    window.print();
  };

  const handleCopy = () => {
    const text = `
Investment Report: ${data.companyName}
Recommendation: ${data.recommendation} (Confidence: ${data.confidence}%)

Overview:
${data.overview}

Reasoning:
${data.reasoning}
    `;
    navigator.clipboard.writeText(text);
    toast.success("Report summary copied to clipboard!");
  };

  const formatCurrency = (value: number) => {
    if (!value) return "N/A";
    if (value >= 1e12) return `$${(value / 1e12).toFixed(2)}T`;
    if (value >= 1e9) return `$${(value / 1e9).toFixed(2)}B`;
    if (value >= 1e6) return `$${(value / 1e6).toFixed(2)}M`;
    return `$${value.toLocaleString()}`;
  };

  return (
    <div className="w-full max-w-5xl mx-auto space-y-8 my-12 print:my-0 pb-20">
      <div className="flex justify-between items-center print:hidden">
        <h2 className="text-2xl font-bold tracking-tight">Investment Analysis Report</h2>
        <div className="flex gap-4">
          <Button variant="outline" onClick={handleCopy}>
            <Copy className="h-4 w-4 mr-2" /> Copy Summary
          </Button>
          <Button onClick={handlePrint}>
            <Printer className="h-4 w-4 mr-2" /> Export PDF
          </Button>
        </div>
      </div>

      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5 }}
      >
        <Card className="border-2 border-primary/20 bg-gradient-to-br from-card to-primary/5">
          <CardHeader className="text-center pb-8">
            <Badge variant="outline" className="w-max mx-auto mb-4">{data.financials?.sector || "Technology"}</Badge>
            <CardTitle className="text-5xl font-extrabold tracking-tight mb-2">{data.companyName}</CardTitle>
            <CardDescription className="text-lg">Generated by InsideIIM AI Research Agent</CardDescription>
          </CardHeader>
          <CardContent className="flex flex-col items-center border-t border-white/10 pt-8">
            <div className="flex flex-col items-center space-y-4">
              <h3 className="text-xl text-muted-foreground uppercase tracking-widest font-semibold">Final Recommendation</h3>
              <div className={`text-6xl font-black ${
                data.recommendation === "BUY" ? "text-green-500" :
                data.recommendation === "AVOID" ? "text-red-500" : "text-yellow-500"
              }`}>
                {data.recommendation}
              </div>
              
              <div className="w-full max-w-md mt-6 space-y-2">
                <div className="flex justify-between text-sm">
                  <span>Confidence Score</span>
                  <span className="font-bold">{data.confidence}%</span>
                </div>
                <Progress value={data.confidence} className="h-3" />
              </div>
            </div>
            
            <div className="mt-12 text-center max-w-3xl">
              <p className="text-lg leading-relaxed text-muted-foreground">{data.reasoning}</p>
            </div>
          </CardContent>
        </Card>
      </motion.div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
        <motion.div initial={{ opacity: 0, x: -20 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.2 }}>
          <Card className="h-full">
            <CardHeader>
              <CardTitle className="flex items-center gap-2"><DollarSign className="text-primary" /> Financial Snapshot</CardTitle>
            </CardHeader>
            <CardContent className="grid grid-cols-2 gap-4">
              <div className="space-y-1">
                <p className="text-sm text-muted-foreground">Market Cap</p>
                <p className="text-xl font-bold">{formatCurrency(data.financials?.marketCap)}</p>
              </div>
              <div className="space-y-1">
                <p className="text-sm text-muted-foreground">Total Revenue</p>
                <p className="text-xl font-bold">{formatCurrency(data.financials?.totalRevenue)}</p>
              </div>
              <div className="space-y-1">
                <p className="text-sm text-muted-foreground">Trailing P/E</p>
                <p className="text-xl font-bold">{data.financials?.trailingPE ? data.financials.trailingPE.toFixed(2) : "N/A"}</p>
              </div>
              <div className="space-y-1">
                <p className="text-sm text-muted-foreground">Profit Margin</p>
                <p className="text-xl font-bold">{data.financials?.profitMargins ? (data.financials.profitMargins * 100).toFixed(2) + "%" : "N/A"}</p>
              </div>
              <div className="space-y-1">
                <p className="text-sm text-muted-foreground">Revenue Growth</p>
                <p className="text-xl font-bold">{data.financials?.revenueGrowth ? (data.financials.revenueGrowth * 100).toFixed(2) + "%" : "N/A"}</p>
              </div>
            </CardContent>
          </Card>
        </motion.div>

        <motion.div initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.3 }}>
          <Card className="h-full">
            <CardHeader>
              <CardTitle className="flex items-center gap-2"><Newspaper className="text-primary" /> Business Overview</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-sm leading-relaxed text-muted-foreground">{data.overview}</p>
            </CardContent>
          </Card>
        </motion.div>
      </div>

      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.4 }}>
        <Card>
          <CardHeader>
            <CardTitle>SWOT & Risk Analysis</CardTitle>
          </CardHeader>
          <CardContent className="grid grid-cols-1 md:grid-cols-2 gap-8">
            <div className="space-y-6">
              <div>
                <h4 className="flex items-center gap-2 text-green-500 font-semibold mb-3"><TrendingUp className="h-4 w-4" /> Strengths</h4>
                <ul className="list-disc pl-5 space-y-1 text-sm text-muted-foreground">
                  {data.strengths?.map((s: string, i: number) => <li key={i}>{s}</li>)}
                </ul>
              </div>
              <div>
                <h4 className="flex items-center gap-2 text-blue-500 font-semibold mb-3"><ShieldCheck className="h-4 w-4" /> Opportunities</h4>
                <ul className="list-disc pl-5 space-y-1 text-sm text-muted-foreground">
                  {data.opportunities?.map((s: string, i: number) => <li key={i}>{s}</li>)}
                </ul>
              </div>
            </div>
            <div className="space-y-6">
              <div>
                <h4 className="flex items-center gap-2 text-orange-500 font-semibold mb-3"><AlertTriangle className="h-4 w-4" /> Weaknesses</h4>
                <ul className="list-disc pl-5 space-y-1 text-sm text-muted-foreground">
                  {data.weaknesses?.map((s: string, i: number) => <li key={i}>{s}</li>)}
                </ul>
              </div>
              <div>
                <h4 className="flex items-center gap-2 text-red-500 font-semibold mb-3"><AlertTriangle className="h-4 w-4" /> Threats & Risks</h4>
                <ul className="list-disc pl-5 space-y-1 text-sm text-muted-foreground">
                  {[...(data.threats || []), ...(data.risks || [])].map((s: string, i: number) => <li key={i}>{s}</li>)}
                </ul>
              </div>
            </div>
          </CardContent>
        </Card>
      </motion.div>

      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.5 }}>
        <Card>
          <CardHeader>
            <CardTitle>Recent News Context</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              {data.news?.map((item: any, i: number) => (
                <a href={item.link} target="_blank" rel="noopener noreferrer" key={i} className="block group">
                  <div className="flex flex-col space-y-1 border-b border-border pb-4 last:border-0 last:pb-0 hover:bg-white/5 p-3 rounded-lg transition-colors">
                    <h5 className="font-medium group-hover:text-primary transition-colors line-clamp-1">{item.title}</h5>
                    <div className="flex items-center justify-between text-xs text-muted-foreground">
                      <span>{item.publisher}</span>
                      <span>{item.publishedAt ? new Date(item.publishedAt).toLocaleDateString() : ""}</span>
                    </div>
                  </div>
                </a>
              ))}
            </div>
          </CardContent>
        </Card>
      </motion.div>

      <div className="text-center text-sm text-muted-foreground py-8">
        <p className="font-semibold text-primary mb-2">Sources:</p>
        <p>{data.sources?.join(" • ")}</p>
        <Separator className="my-6 max-w-md mx-auto" />
        <p className="text-xs max-w-2xl mx-auto">
          Disclaimer: This report is generated by an AI agent and is for educational and demonstrative purposes only. 
          It does not constitute financial advice. Always conduct your own research or consult a licensed financial advisor before making investment decisions.
        </p>
      </div>
    </div>
  );
}
