import { motion } from "framer-motion";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { Button } from "@/components/ui/button";
import { Printer, Copy, TrendingUp, AlertTriangle, ShieldCheck, Newspaper, DollarSign, Activity } from "lucide-react";
import { toast } from "sonner";
import { Progress } from "@/components/ui/progress";

const containerVariants = {
  hidden: { opacity: 0 },
  show: {
    opacity: 1,
    transition: { staggerChildren: 0.1 }
  }
};

const itemVariants = {
  hidden: { opacity: 0, y: 15 },
  show: { opacity: 1, y: 0, transition: { stiffness: 120 } }
};

export function InvestmentReport({ data }: { data: any }) {
  const handlePrint = () => {
    window.print();
  };

  const handleCopy = () => {
    const text = `
Investment Report: ${data.companyName}
Recommendation: ${data.recommendation} (Confidence: ${data.confidence}%)

Overview:
${data.overview}

Reasoning:
${data.reasoning}
    `;
    navigator.clipboard.writeText(text);
    toast.success("Report summary copied to clipboard!");
  };

  const formatCurrency = (value: number) => {
    if (!value) return "N/A";
    if (value >= 1e12) return `$${(value / 1e12).toFixed(2)}T`;
    if (value >= 1e9) return `$${(value / 1e9).toFixed(2)}B`;
    if (value >= 1e6) return `$${(value / 1e6).toFixed(2)}M`;
    return `$${value.toLocaleString()}`;
  };

  return (
    <div className="w-full max-w-6xl mx-auto space-y-8 my-12 print:my-0 pb-20 relative">
      {/* Decorative background glow for the report */}
      <div className="absolute top-20 left-1/2 -translate-x-1/2 w-[800px] h-[400px] bg-primary/5 rounded-full blur-[120px] pointer-events-none -z-10" />

      <div className="flex justify-between items-center print:hidden border-b border-border pb-6">
        <div>
          <h2 className="text-3xl font-extrabold tracking-tight bg-clip-text text-transparent bg-gradient-to-r from-white to-white/60">
            Investment Analysis Report
          </h2>
          <p className="text-muted-foreground mt-1">Comprehensive AI-generated insights</p>
        </div>
        <div className="flex gap-4">
          <Button variant="outline" onClick={handleCopy} className="hover:bg-white/10 transition-colors">
            <Copy className="h-4 w-4 mr-2" /> Copy Summary
          </Button>
          <Button onClick={handlePrint} className="shadow-[0_0_15px_rgba(255,255,255,0.1)] hover:shadow-[0_0_25px_rgba(255,255,255,0.2)] transition-shadow">
            <Printer className="h-4 w-4 mr-2" /> Export PDF
          </Button>
        </div>
      </div>

      <motion.div
        initial={{ opacity: 0, scale: 0.98 }}
        animate={{ opacity: 1, scale: 1 }}
        transition={{ duration: 0.5, ease: "easeOut" }}
      >
        <Card className="border border-primary/20 bg-black/40 backdrop-blur-2xl overflow-hidden relative group">
          <div className="absolute inset-0 bg-gradient-to-br from-primary/10 via-transparent to-transparent opacity-50 group-hover:opacity-70 transition-opacity duration-700" />
          
          <CardHeader className="text-center pb-8 pt-12 relative z-10">
            <Badge variant="secondary" className="w-max mx-auto mb-6 px-4 py-1 text-sm bg-primary/20 text-primary-foreground border-primary/30">
              {data.financials?.sector || "Technology"}
            </Badge>
            <CardTitle className="text-6xl font-black tracking-tighter mb-4">{data.companyName}</CardTitle>
            <CardDescription className="text-xl font-medium text-muted-foreground">Generated by InsideIIM AI Research Agent</CardDescription>
          </CardHeader>
          <CardContent className="flex flex-col items-center border-t border-white/5 pt-10 relative z-10 bg-gradient-to-b from-transparent to-background/50">
            <div className="flex flex-col items-center space-y-6 w-full max-w-2xl">
              <div className="flex items-center gap-2">
                <Activity className="h-5 w-5 text-muted-foreground" />
                <h3 className="text-sm text-muted-foreground uppercase tracking-[0.3em] font-bold">Final Verdict</h3>
              </div>
              
              <div className="relative">
                {/* Glow behind text */}
                <div className={`absolute inset-0 blur-2xl opacity-40 ${
                  data.recommendation === "BUY" ? "bg-green-500" :
                  data.recommendation === "AVOID" ? "bg-red-500" : "bg-yellow-500"
                }`} />
                <div className={`text-8xl font-black tracking-tighter relative z-10 drop-shadow-2xl ${
                  data.recommendation === "BUY" ? "text-green-400" :
                  data.recommendation === "AVOID" ? "text-red-400" : "text-yellow-400"
                }`}>
                  {data.recommendation}
                </div>
              </div>
              
              <div className="w-full mt-8 p-6 rounded-2xl bg-white/5 border border-white/10 backdrop-blur-md">
                <div className="flex justify-between text-sm mb-3 font-medium">
                  <span className="text-muted-foreground uppercase tracking-wider">AI Confidence Score</span>
                  <span className="text-white font-bold text-lg">{data.confidence}%</span>
                </div>
                <div className="relative h-3 w-full bg-white/10 rounded-full overflow-hidden">
                  <motion.div 
                    initial={{ width: 0 }}
                    animate={{ width: `${data.confidence}%` }}
                    transition={{ duration: 1.5, ease: "easeOut", delay: 0.5 }}
                    className={`absolute top-0 left-0 h-full rounded-full ${
                      data.recommendation === "BUY" ? "bg-gradient-to-r from-green-600 to-green-400" :
                      data.recommendation === "AVOID" ? "bg-gradient-to-r from-red-600 to-red-400" : "bg-gradient-to-r from-yellow-600 to-yellow-400"
                    }`}
                  />
                </div>
              </div>
            </div>
            
            <div className="mt-14 text-center max-w-4xl mx-auto px-4">
              <p className="text-xl leading-relaxed text-foreground/90 font-medium">{data.reasoning}</p>
            </div>
          </CardContent>
        </Card>
      </motion.div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.2 }} className="lg:col-span-1">
          <Card className="h-full bg-black/40 backdrop-blur-xl border-white/10 hover:border-white/20 transition-colors">
            <CardHeader className="border-b border-white/5 pb-4">
              <CardTitle className="flex items-center gap-3 text-xl"><DollarSign className="text-primary h-6 w-6" /> Financial Snapshot</CardTitle>
            </CardHeader>
            <CardContent className="pt-6 grid grid-cols-2 gap-y-8 gap-x-4">
              <div className="space-y-2">
                <p className="text-xs text-muted-foreground uppercase tracking-wider font-semibold">Market Cap</p>
                <p className="text-2xl font-bold tracking-tight">{formatCurrency(data.financials?.marketCap)}</p>
              </div>
              <div className="space-y-2">
                <p className="text-xs text-muted-foreground uppercase tracking-wider font-semibold">Total Revenue</p>
                <p className="text-2xl font-bold tracking-tight">{formatCurrency(data.financials?.totalRevenue)}</p>
              </div>
              <div className="space-y-2">
                <p className="text-xs text-muted-foreground uppercase tracking-wider font-semibold">Trailing P/E</p>
                <p className="text-2xl font-bold tracking-tight">{data.financials?.trailingPE ? data.financials.trailingPE.toFixed(2) : "N/A"}</p>
              </div>
              <div className="space-y-2">
                <p className="text-xs text-muted-foreground uppercase tracking-wider font-semibold">Profit Margin</p>
                <p className="text-2xl font-bold tracking-tight text-green-400">{data.financials?.profitMargins ? (data.financials.profitMargins * 100).toFixed(2) + "%" : "N/A"}</p>
              </div>
              <div className="space-y-2">
                <p className="text-xs text-muted-foreground uppercase tracking-wider font-semibold">Revenue Growth</p>
                <p className="text-2xl font-bold tracking-tight">{data.financials?.revenueGrowth ? (data.financials.revenueGrowth * 100).toFixed(2) + "%" : "N/A"}</p>
              </div>
            </CardContent>
          </Card>
        </motion.div>

        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.3 }} className="lg:col-span-2">
          <Card className="h-full bg-black/40 backdrop-blur-xl border-white/10 hover:border-white/20 transition-colors">
            <CardHeader className="border-b border-white/5 pb-4">
              <CardTitle className="flex items-center gap-3 text-xl"><Newspaper className="text-primary h-6 w-6" /> Executive Overview</CardTitle>
            </CardHeader>
            <CardContent className="pt-6">
              <p className="text-base leading-loose text-muted-foreground/90 font-medium">{data.overview}</p>
            </CardContent>
          </Card>
        </motion.div>
      </div>

      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.4 }}>
        <Card className="bg-black/40 backdrop-blur-xl border-white/10 overflow-hidden">
          <div className="h-1 w-full bg-gradient-to-r from-green-500 via-blue-500 to-red-500 opacity-50" />
          <CardHeader className="border-b border-white/5 bg-white/[0.02]">
            <CardTitle className="text-2xl font-bold">SWOT & Risk Architecture</CardTitle>
          </CardHeader>
          <CardContent className="grid grid-cols-1 md:grid-cols-2 gap-x-12 gap-y-12 pt-8">
            <div className="space-y-10">
              <motion.div variants={containerVariants} initial="hidden" animate="show">
                <h4 className="flex items-center gap-3 text-green-400 font-bold text-lg mb-6 tracking-wide uppercase">
                  <TrendingUp className="h-5 w-5" /> Strengths
                </h4>
                <ul className="space-y-4">
                  {data.strengths?.map((s: string, i: number) => (
                    <motion.li variants={itemVariants} key={i} className="flex gap-3 text-muted-foreground leading-relaxed">
                      <div className="mt-1.5 h-1.5 w-1.5 rounded-full bg-green-500/50 flex-shrink-0" />
                      <span>{s}</span>
                    </motion.li>
                  ))}
                </ul>
              </motion.div>
              
              <Separator className="bg-white/5" />
              
              <motion.div variants={containerVariants} initial="hidden" animate="show">
                <h4 className="flex items-center gap-3 text-blue-400 font-bold text-lg mb-6 tracking-wide uppercase">
                  <ShieldCheck className="h-5 w-5" /> Opportunities
                </h4>
                <ul className="space-y-4">
                  {data.opportunities?.map((s: string, i: number) => (
                    <motion.li variants={itemVariants} key={i} className="flex gap-3 text-muted-foreground leading-relaxed">
                      <div className="mt-1.5 h-1.5 w-1.5 rounded-full bg-blue-500/50 flex-shrink-0" />
                      <span>{s}</span>
                    </motion.li>
                  ))}
                </ul>
              </motion.div>
            </div>
            
            <div className="space-y-10">
              <motion.div variants={containerVariants} initial="hidden" animate="show">
                <h4 className="flex items-center gap-3 text-orange-400 font-bold text-lg mb-6 tracking-wide uppercase">
                  <AlertTriangle className="h-5 w-5" /> Weaknesses
                </h4>
                <ul className="space-y-4">
                  {data.weaknesses?.map((s: string, i: number) => (
                    <motion.li variants={itemVariants} key={i} className="flex gap-3 text-muted-foreground leading-relaxed">
                      <div className="mt-1.5 h-1.5 w-1.5 rounded-full bg-orange-500/50 flex-shrink-0" />
                      <span>{s}</span>
                    </motion.li>
                  ))}
                </ul>
              </motion.div>
              
              <Separator className="bg-white/5" />
              
              <motion.div variants={containerVariants} initial="hidden" animate="show">
                <h4 className="flex items-center gap-3 text-red-400 font-bold text-lg mb-6 tracking-wide uppercase">
                  <AlertTriangle className="h-5 w-5" /> Threats & Risks
                </h4>
                <ul className="space-y-4">
                  {[...(data.threats || []), ...(data.risks || [])].map((s: string, i: number) => (
                    <motion.li variants={itemVariants} key={i} className="flex gap-3 text-muted-foreground leading-relaxed">
                      <div className="mt-1.5 h-1.5 w-1.5 rounded-full bg-red-500/50 flex-shrink-0" />
                      <span>{s}</span>
                    </motion.li>
                  ))}
                </ul>
              </motion.div>
            </div>
          </CardContent>
        </Card>
      </motion.div>

      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.5 }}>
        <Card className="bg-black/40 backdrop-blur-xl border-white/10">
          <CardHeader className="border-b border-white/5">
            <CardTitle className="text-xl">Market Intelligence & News</CardTitle>
            <CardDescription>Latest catalysts and market events</CardDescription>
          </CardHeader>
          <CardContent className="pt-6">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {data.news?.slice(0, 4).map((item: any, i: number) => (
                <motion.a 
                  href={item.link} 
                  target="_blank" 
                  rel="noopener noreferrer" 
                  key={i} 
                  className="block group"
                  whileHover={{ scale: 1.02 }}
                  transition={{ type: "spring", stiffness: 400, damping: 25 }}
                >
                  <div className="flex flex-col h-full bg-white/[0.03] border border-white/5 hover:border-primary/30 p-5 rounded-xl transition-colors">
                    <h5 className="font-semibold text-[15px] group-hover:text-primary transition-colors line-clamp-2 leading-snug mb-4">{item.title}</h5>
                    <div className="mt-auto flex items-center justify-between text-xs text-muted-foreground/70 font-medium">
                      <span className="uppercase tracking-wider">{item.publisher}</span>
                      <span>{item.publishedAt ? new Date(item.publishedAt).toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' }) : ""}</span>
                    </div>
                  </div>
                </motion.a>
              ))}
            </div>
          </CardContent>
        </Card>
      </motion.div>

      <div className="text-center text-sm text-muted-foreground py-12">
        <p className="font-semibold text-primary/70 uppercase tracking-widest mb-3 text-xs">Data Verified Sources</p>
        <p className="opacity-70">{data.sources?.join(" • ")}</p>
        <Separator className="my-8 max-w-md mx-auto bg-white/5" />
        <p className="text-[11px] uppercase tracking-wider max-w-3xl mx-auto opacity-50 leading-relaxed">
          Disclaimer: This report is generated by an AI agent (Gemini 3.5 Flash) and is for educational and demonstrative purposes only. 
          It does not constitute financial advice. Always conduct your own research or consult a licensed financial advisor before making investment decisions.
        </p>
      </div>
    </div>
  );
}
